### ISSUE TITLE
No License specified

### ISSUE THREAD

**Issue by danbolinson** [jjorissen52/bullhorn_interface#12]
Hi there,

I'd potentially be interested in using this repo but looks like no license has been specified! Is your intention for this to be open-sourced?

Cheers

Dan

**Comment by jjorissen52** [comment]
Hey Dan, thanks for bringing this to my attention. This repository uses the Apache License, Version 2.

https://github.com/jjorissen52/bullhorn_interface/blob/master/LICENSE.txt
